### ISSUE TITLE
Short method use of formatMessage() -> i18n.t()

### ISSUE THREAD

**Issue by zzhenryquezz** [adonisjs/i18n#118]
## Why this feature is required (specific use-cases will be appreciated)?

It's a common way of use in i18n packages and the code lines are more clean this way

```ts
i18n.formatMessage('created', [i18n.formatMessage('lead')])
```

```ts
i18n.t('created', [i18n.t('lead')])
```

## Have you tried any other work arounds?
Yeah a use utils method that makes this for me but it would be nice to have this natively in the module

## Are you willing to work on it with little guidance?

Sure

**Comment by thetutlage** [comment]
Yeah, kind of makes sense. Maybe you can also update the view global to use the `t` method as well. https://github.com/adonisjs/i18n/blob/develop/src/Bindings/View.ts#L30

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
