### ISSUE TITLE
Problem with validator when using i18n

### ISSUE THREAD

**Issue by yung-esco** [adonisjs/i18n#120]
There is a problem when error messages with rules containing options are configured via the i18n module. Indeed, the options are not recognized and this generates an error. Example: The rule below works normally when hard-coded into the validator

public messages: CustomMessages = {
    distinct: "The {{ options.field }} value for {{ field }} must be unique"
  }

But when it is integrated into the file (validator.yaml/validator.json) there is an error like

{
    "message": "Cannot read properties of undefined (reading 'errors')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'errors')\n at SchedulingsController.store (C:\\Users\\User\\anlabstech\\CANAL OLYMPIA APP\\api\\app\\Controllers \\Http\\Admin\\SchedulingsController.ts:29:63)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at Object.PreCompiler.runRouteHandler [as fn] (C:\\ Users\\User\\anlabstech\\CANAL OLYMPIA APP\\api\\node_modules\\@adonisjs\\http-server\\build\\src\\Server\\PreCompiler\\index.js:47:31)\ n at RequireAdminAuth.handle (C:\\Users\\User\\anlabstech\\CANAL OLYMPIA APP\\api\\app\\Middleware\\RequireAdminAuth.ts:31:5)\n at DetectUserLocale.handle (C: \\Users\\User\\anlabstech\\CANAL OLYMPIA APP\\api\\app\\Middleware\\DetectUserLocale.ts:50:5)\n at Server.handleRequest (C:\\Users\\User\\ anlabstech\\CANAL OLYMPIA APP\\api\\node_modules\\@adonisjs\\http-server\\build\\src\\Server\\index.js:108:13)"
}

**Comment by thetutlage** [comment]
The error message says `Cannot read properties of undefined (reading 'errors')`. Not sure how is this related to using i18n for error messages.

Can you please the controller using the validator and also the JSON files with messages

**Comment by yung-esco** [comment]
> The error message says `Cannot read properties of undefined (reading 'errors')`. Not sure how is this related to using i18n for error messages.
> 
> Can you please the controller using the validator and also the translations JSON file?

Of course

Source of validator.yaml -->

shared:
  required: "The {field} field is mandatory"
  number: The {field} field must be a valid number
  range: The field {field} must be between { start } and { stop } years
  enum: "The {field} field must be one of the { choices }"
  unique: The value for field {field} must be unique
  url: The value of {field} is not a valid url
  "date.format": The date format for {field} is not valid
  exists: The reference constraint(s) for {field} is not satisfied
  distinct: "The { options.field } value for { field } must be unique"
  afterOrEqual: The {field} field cannot be in past


My Validator -->


import { schema, CustomMessages, rules } from '@ioc:Adonis/Core/Validator'
import type { HttpContextContract } from '@ioc:Adonis/Core/HttpContext'
import { DateTime } from 'luxon'

export default class CreateSchedulingValidator {
  constructor(protected ctx: HttpContextContract) {}

  public refs = schema.refs({
    allowedDate: DateTime.now()
  })


  public schema = schema.create({
    start_at: schema.date({}, [
      rules.afterOrEqual(this.refs.allowedDate)
    ]),
    end_at: schema.date({}, [
      rules.afterField('start_at')
    ]),
    movie_id: schema.number([
      rules.exists({
        table: 'movies',
        column: 'id',
        where: {
          active: 1,
          deleted: 0
        }
      })
    ]),
    movie_room_id: schema.number([
      rules.exists({
        table: 'movie_rooms',
        column: 'id',
        where: {
          active: 1,
          deleted: 0
        }
      })
    ]),
    packages: schema.array([
      rules.distinct('label')
    ]).members(schema.object().members({
      price: schema.number([
        rules.unsigned()
      ]),
      label: schema.string(),
      description: schema.string(),
      places: schema.number([
        rules.unsigned(),
        rules.range(0, 255)
      ])
    }))
  })

  public messages: CustomMessages = {}
}


A chunk of my controller method -->


        const user = await ctx.auth.use('api').user!

        let form_data: any

        try {
            form_data = await ctx.request.validate(CreateMovieValidator)
        } catch(e) {

            if(Env.get('NODE_ENV') === 'development') {
                console.log(e)
            }

            return ApiResponseUtils.bad_input(ctx, e.messages.errors)
        }

        // Check if the movie doesn't exists
        const exists = await Movie.query().where({
            title: form_data.title,
            year: form_data.year,
            lang: form_data.lang
        }).first()

        if(exists) {
            return ApiResponseUtils.bad_request(ctx, ctx.i18n.formatMessage('messages.text_movie_exists'))
        }

**Comment by thetutlage** [comment]
Can you please format the code blocks properly, it's kind of hard to scan them. Here's a quick guide from Github on the same https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by yung-esco** [comment]
> Can you please format the code blocks properly, it's kind of hard to scan them. Here's a quick guide from Github on the same https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

Hello
It's ok can you check it ?
