### ISSUE TITLE
Wrong date formatting in czech localization

### ISSUE THREAD

**Issue by anaq1** [adonisjs/i18n#122]
## Package version
1.5.6

## Node.js and npm version
Node.js 18.4.0
npm 18.12.1

## Sample Code (to reproduce the issue)
I18n.locale('cz').formatDate(new Date()) 

output:
10/10/2022
expected:
10. 10. 2022

**Comment by thetutlage** [comment]
The native JavaScript API returns the same as well. Following is a screenshot from the chrome dev tools.

Maybe you want to use `cs-cz`

<img width="626" alt="Screenshot 2022-10-10 at 10 06 50 PM" src="https://user-images.githubusercontent.com/1706381/194914188-16e14f67-a292-40bc-b09c-24640b90a2be.png">

**Comment by anaq1** [comment]
Indeed... Looks like JS accepts only "cs" or "cs-cz", but "cz" gives the default format with slashes. Thank you, this issue can be closed.
