### ISSUE TITLE
Choose how missing translations are returned

### ISSUE THREAD

**Issue by Barsnes** [adonisjs/i18n#123]
When using `i18n.formatMessage("system.hello")` to get a translation, it currently returns `translation missing: en, system.hello` if the translations does not exist.

My feature request is to be able to just return the key if a translation is missing.

E.x.: 
`i18n.formatMessage("system.hello")` would return `system.hello` if the translation does not exist.

A possible solution is to add a config parameter that let's you define if you want missing translations to return a key, or the current error message.

**Comment by Barsnes** [comment]
i have made a pull request with the changes proposed: https://github.com/adonisjs/i18n/pull/124

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
