### ISSUE TITLE
How to change the locale by depends on user's country

### ISSUE THREAD

**Issue by adnanerlansyah403** [adonisjs/i18n#126]
Hello sir , i want to ask

So how can i change the defaultLocale of configure i18n in config/i18n.ts file after i set it before. Because when i'm using formatMessage method from i81n i always get the messages from defaultLocale and not from locale that i set even though i already changed it. The code example is below :

`I81n.locale('en').formatMessage('messages.not_found')`

So when i write that code the messages is still from defaultalocale, it's 'id' for initialze of indonesian bahasa. And not using messages of en

So how to fix this issue sir, thank you so much

**Comment by thetutlage** [comment]
Please share the complete code example that I can use to reproduce the behavior?

**Comment by adnanerlansyah403** [comment]
> Please share the complete code example that I can use to reproduce the behavior?

Sry sir this is my code :

**config/i81n.ts**
```
import Application from '@ioc:Adonis/Core/Application'
import { I18nConfig } from '@ioc:Adonis/Addons/I18n'

let i18nConfig: I18nConfig  = {
  translationsFormat: 'icu',
  defaultLocale: 'id',
  supportedLocales: ['en', 'id'], // Daftar bahasa yang didukung
  fallbackLocales: {
    'en': 'en', // Bahasa pengganti untuk bahasa Inggris
    'id': 'en', // Bahasa pengganti untuk bahasa Indonesia
  },
  provideValidatorMessages: true,
  loaders: {
    fs: {
      enabled: true,
      location: Application.resourcesPath('lang'),
    },
  },
}

export default i18nConfig
```

**App/Exceptions/Handler.ts**
```
import Logger from '@ioc:Adonis/Core/Logger'
import HttpExceptionHandler from '@ioc:Adonis/Core/HttpExceptionHandler'
import I18n from '@ioc:Adonis/Addons/I18n'

export default class ExceptionHandler extends HttpExceptionHandler {
  constructor () {
    super(Logger)
  }

  public async handle(error: any, ctx: HttpContextContract) {
    /**
     * Self handle the validation exception
     */
    if (error.code == 'E_ROW_NOT_FOUND') {
      return ctx.response.status(error.status).send({
        status: false,
        message: I18n.locale().formatMessage('messages.not_found', { data: ctx.route.handler.split('.')[0].replace('sC', "").replace("ontroller", "") }),
        data: null
      })
    }

    /**
     * Forward rest of the exceptions to the parent class
     */
    return super.handle(error, ctx)
  }
}
```

**Comment by adnanerlansyah403** [comment]
> Please share the complete code example that I can use to reproduce the behavior?

How sir, did u already find the issue ?

**Comment by RomainLanz** [comment]
Hey @adnanerlansyah403! 👋🏻 

You are using `I18n.locale()`, but the method `locale()` except to receive the local you want to use.

📚 https://docs.adonisjs.com/guides/i18n#locale-matching
