### ISSUE TITLE
i18n not working on tests

### ISSUE THREAD

**Issue by assaad97** [adonisjs/i18n#127]
im trying to do an api test using adonsjs test suite, i define the router, that calls a controller and the controller calls a service class. in this service class i call i18n to do translations (check the code snippet below).

when im running the test i get an error `Error: TypeError: this.formatMessage is not a function` on AuthServices.

when i try to handle translations on AuthException i get missing translations error `translation missing: en, E_AUTH_NOT_FOUND: auth.errors.userNotFound`

when i call the route using postman it works.

nothing is mentionned on the documentation about using i18n inside tests.

i don't know is an additional configuration is needed (if its the case let me know and sorry that i didn't catch it  😅) or if its something that i missed, or if its an actual bug.

thank you in advance for the response.

## Package version
@adonisjs/i18n v1.6.0

## Node.js and npm version
node v18.16.0 npm v9.5.1

## Sample Code (to reproduce the issue)
// router
```
    function AuthRoutes(controller: AuthController) {
        Route.group(() => {
            // sign out route
            Route.post("/signout", (ctx) => controller.signOut(ctx)).as("signout");

            // ... the rest of the routes
        })
        .prefix("/auth")
        .as("auth");
    }
```

// AuthController
```
    class AuthController {
        private _authService: AuthServices = new AuthServices();
        // ... some attributes

        public async signOut({ request, response, i18n }: HttpContextContract) {
            // ... some logic

            // calls the service
            await this._authService.signout(...args);

            // return http response
            response.status(200).json({
                success: true,
                message: i18n.t("auth.signout.message"),
            });
        }

        // ... some methods
    }
```

// AuthServices
```
    class AuthServices {
        private readonly _translator = i18n.locale(i18n.defaultLocale).t;
        // ...some attributes

        public async disconnect(...args) {
            // ... some logic

            if (error)
                throw new this.authException(
                    this.translator("auth.errors.errorMessage"),
                    400,
                    "E_AUTH_FAILED_LOGOUT"
                );

            // ... some logic
        }
    }
```

// AuthException
```
    class AuthExceptions extends Exception {
        public async handle(error: this, ctx: HttpContextContract) {
            const { response, request, i18n } = ctx;

            switch (error.code) {
                case "E_AUTH_FAILED_LOGOUT": {
                    response.status(error.status).json({
                        success: false,
                        message: i18n.t(error.message),
                        errorCode: error.code,
                        path: request.url(),
                    });
                }

                // ... other cases

                default: {
                    return super.handle(error, ctx);
                }
            }
        }
    }
```

**Comment by RomainLanz** [comment]
Hey @assaad97! 👋🏻 

Please, provide a repository with the code to reproduce your issue.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
