### ISSUE TITLE
Cannot find module '@adonisjs/i18n/types'

### ISSUE THREAD

**Issue by m-i-c-h-a-l** [adonisjs/i18n#134]
### Package version

2.1.0

### Describe the bug

I followed instructions for custom translation loader from https://docs.adonisjs.com/guides/digging-deeper/i18n#creating-a-custom-translation-loader. I am not able to compile the project with the code from the doc. If I ignore the compilation error, the loader itself is working as expected.

Steps to reproduce:
1. Create a new project
2. Add i18n with node ace command.
3. Add custom loader code from docs (simple copy-paste).
4. Try to build the project.

Result:
error TS2307: Cannot find module '@adonisjs/i18n/types' or its corresponding type declarations.

IDE (Intellij IDEA) also shows this error.

### Reproduction repo
https://github.com/m-i-c-h-a-l/adonisjs-i18n-bug-repo

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by m-i-c-h-a-l** [comment]
I am not sure, what is wrong with the issue description - it includes everything needed, maybe except the reproduction repository, because it is very easily reproducible. I created a repo with the issue and updated the description, in case this was the problem.

**Comment by thetutlage** [comment]
Can you point me where is the implementation of the custom loader in the shared repository?

**Comment by m-i-c-h-a-l** [comment]
Sure: https://github.com/m-i-c-h-a-l/adonisjs-i18n-bug-repo/blob/master/app/middleware/loader.ts

**Comment by thetutlage** [comment]
Thanks. Let me look into it.

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/i18n/commit/beaee6e01cd50f437a5ead4261dd5da3792f463a

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/i18n/releases/tag/v2.1.1
