### ISSUE TITLE
Json files for resources/lang

### ISSUE THREAD

**Issue by alejandrosramirez** [adonisjs/i18n#93]
Hi.

I am developing an API in the most recent version of the framework and I would be interested to know what all the language files that are hosted in the `resources/lang` folder are called, it turns out that I want to handle the errors from the API to report to the frontend in Spanish language and only the `validator.json` and `auth.json` files are explained in the documentation.

**Comment by joaovfsousa** [comment]
Hi @alejandrosramirez, just confirming, you are meaning to translate your own custom errors' messages, right?

**Comment by alejandrosramirez** [comment]
Hi @joaovfsousa.

Yes, I'm looking for the correct way to define the files and the structure of each one to translate the errors, for example I saw that they can be used with the extension .json or .yaml / .yml.

**Comment by joaovfsousa** [comment]
Ok, I don't think there is a "correct" way to do this, since we are talking about your own "custom" exceptions. So here's how I've been doing it, hope it can help you.

I've been using adonis in some jobs and I generally define shared exceptions under `app/Exceptions` and some domain exceptions in a `exceptions.ts` file under the controller directory. So, define a `exceptions.json` file for all this exceptions translations and use a structure like this: 
```
{
  "shared": {<sharedExceptions> },
  "middleware": {
    "<middlewareName>": {
      "<exceptionName>": "Translation"
    }
   },
   "controller": {
    "<controllerName>": {
      "<exceptionName>": "Translation"
    }
  }
}
```
A example of a `ForbiddenException` already using translations:
```
import BaseException from '../BaseException'
import HttpContext from '@ioc:Adonis/Core/HttpContext'

export default class ForbiddenException extends BaseException {
  constructor() {
    const ctx = HttpContext.get()!
    const { i18n } = ctx

    const message = i18n.formatMessage('exceptions.shared.forbidden')
    super(`403-ForbiddenNotFound`, 403, message)
  }
}
```

**Comment by alejandrosramirez** [comment]
Ok, I understand, thank you so much.

**Comment by alejandrosramirez** [comment]
I want to know the correct way to access the value of the options of some validators and show the translated text to the frontend, for example `minLength` and `maxLength` to validate a password of at least 8 characters, I want to try with either of the two, but in the documentation the example for `minLength` that comes did not work for me.
Any way to resolve that issue?

I defined the `validator.yaml` file inside `resources/lang/en`

The photo is an example: 

![imagen](https://user-images.githubusercontent.com/36974510/143290705-c64f088a-a371-4a99-a69e-708a7bec11c1.png)
